version: "3.2"

services:
  redis:
    container_name: ${REDIS_HOST}
    image: redis
    networks:
      - app_network
  app:
    container_name: "app"
    env_file:
      - .env
    build:
      context: .
      args:
        - PORT=${APP_PORT}
    ports:
      - ${APP_PORT}:${APP_PORT}
      - 9229:9229
    environment:
      - PORT=${APP_PORT}
    networks:
      - app_network



networks:
  app_network:
    external: false